### ISSUE TITLE
Support liff-inspector via using CDN

### ISSUE THREAD

**Issue by JimmyTai** [line/liff-inspector#11]
Hope you could support this package by using CDN.
Because we are building an LIFF App on Flutter Web. It couldn't include npm module.

**Comment by cola119** [comment]
You can use liff-inspector via CDN by UNKPG. Could you try that?
https://www.unpkg.com/@line/liff-inspector@1.0.2/dist/umd/liff-inspector.js

**Comment by JimmyTai** [comment]
@cola119 
Thank you. I'll try it.
