### ISSUE TITLE
liff-inspector depends on vulnerable version of Webpack

### ISSUE THREAD

**Issue by hylom** [line/liff-inspector#15]
https://github.com/line/liff-inspector/blob/main/packages/liff-inspector/package.json#L21

@line/liff-inspector 1.0.2 depends on "webpack": "5.72.0", but this version of Webpack has high severity vulnerability ( https://github.com/advisories/GHSA-hc6q-2mpp-qw7j ). You need to update Webpack to v5.76.0 or later.

https://github.com/webpack/webpack/releases/tag/v5.76.0

**Comment by cola119** [comment]
Thank you for the report! We'll update the dependencies later.
