### ISSUE TITLE
support "TrustProxies" option

### ISSUE THREAD

**Issue by snmatsui** [line/liff-inspector#5]
When running inspector server behind a proxy like a load balancer, both app client and inspector client access to inspector server with SSL, but the proxy access to inspector server without SSL.

inspector server shows:
DevTools URL: devtools://devtools/bundled/inspector.html?ws=****

correct url is:
DevTools URL: devtools://devtools/bundled/inspector.html?wss=****

Switching display url option is needed like Laravel TrustProxies middleware.

**Comment by cola119** [comment]
@snmatsui Thank you for your feedback! I'm not sure about TrustProxies and proxy server architecture so correct me if I'm wrong.

As you probably know, the protocol is determined according to how you start LIFF Inspector Server, which means in your case, the protocol of the connection between the server and the load balancer is displayed.

https://github.com/line/liff-inspector/blob/5f385f67eee19ad893c66c3d1da1ee0cf1678ae3/packages/headless-inspector/src/server.ts#L166-L170

So I think `X-Forwarded-Proto` would be a better value for detecting the protocol in that case.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto
> To determine the protocol used between the client and the load balancer, the X-Forwarded-Proto request header can be used.

**Comment by snmatsui** [comment]
Thank you for the proposal. Intergrating X-Forwarded-Proto header looks good idea.
